name: MHU_GlobalRanks
version: ${project.version}
main: com.company.Main
api-version: 2.10.0
depend: [HolographicDisplays]
softdepend: []
commands:
  globalrank:
    description: Checks your globalrank
    aliases: []
    usage: /globalrank
  hgtest:
    description: Checks your globalrank
    aliases: []
    usage: /globalrank

